FROM python:3.10.12-alpine3.18
WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip 
RUN pip install --no-cache-dir -r requirements.txt

# ENV FLASK_APP=run.py
# ENV FLASK_RUN_HOST='0.0.0.0'
# ENV FLASK_RUN_PORT=5030
COPY . .
EXPOSE 5030
# ENTRYPOINT [ "flask", "run" ]
ENTRYPOINT [ "python", "run.py" ]
