from dotenv import load_dotenv
import os

load_dotenv()

class TestConfig:
    SECRET_KEY = os.getenv('SECRET_KEY')
    
    #### DATABASE
    TEST_DATABASE_USERNAME = os.getenv('TEST_DATABASE_USERNAME')
    TEST_DATABASE_PASSWORD = os.getenv('TEST_DATABASE_PASSWORD')
    TEST_DATABASE_HOSTNAME = os.getenv('TEST_DATABASE_HOSTNAME')
    TEST_DATABASE_PORT = os.getenv('TEST_DATABASE_PORT')
    TEST_DATABASE_NAME = os.getenv('TEST_DATABASE_NAME')

    SQLALCHEMY_DATABASE_URI = F'postgresql+psycopg2://{TEST_DATABASE_USERNAME}:{TEST_DATABASE_PASSWORD}@{TEST_DATABASE_HOSTNAME}:{TEST_DATABASE_PORT}/{TEST_DATABASE_NAME}'
    SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv('SQLALCHEMY_TRACK_MODIFICATIONS')
