"""empty message

Revision ID: 213db944555d
Revises: 2dc6e6014244
Create Date: 2023-07-03 04:56:27.125977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213db944555d'
down_revision = '2dc6e6014244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), server_default='False', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
